alias: Led Küche 1.3.1
description: "Automatisierung zur Steuerung von Lidl Modlight"
triggers:
  - entity_id:
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_8
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_10
      - binary_sensor.ture_eingang_window_door_is_open
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_7
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_9
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_3
    from: "off"
    to: "on"
    id: zone_on
    trigger: state
  - entity_id: binary_sensor.presence_sensor_fp2_4611_presence_sensor_1
    from: "on"
    to: "off"
    id: anwesend_off
    trigger: state
  - entity_id: sensor.presence_sensor_fp2_4611_light_sensor_light_level
    above: 40
    id: hell
    trigger: numeric_state
conditions: []
actions:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: >-
                  {% set rgb = state_attr('light.lidl_kuche', 'rgb_color') %} {%
                  set color_state = states('input_text.lidl_kuche_rgb_color') |
                  from_json %} {% if rgb is not none and color_state is not none
                  %}
                    {{ [rgb[0] | int, rgb[1] | int, rgb[2] | int] != [color_state[0] | int, color_state[1] | int, color_state[2] | int]
                    and rgb != [252, 252, 252]
                    and states('light.lidl_kuche') == 'on' }}
                  {% else %}
                    false
                  {% endif %}
              - condition: numeric_state
                entity_id: light.lidl_kuche
                attribute: brightness
                below: 80
              - condition: state
                entity_id: input_boolean.lidl_kuche_speicherfreigabe
                state: "on"
        sequence:
          - data:
              entity_id: input_text.lidl_kuche_rgb_color
              value: >
                {% set rgb = state_attr('light.lidl_kuche', 'rgb_color') %} {{
                [rgb[0], rgb[1], rgb[2]] | to_json }}
            action: input_text.set_value
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: numeric_state
                entity_id: sensor.pir_kuche_illuminance
                below: 3
              - condition: trigger
                id: zone_on
        sequence:
          - target:
              entity_id: input_boolean.lidl_kuche_speicherfreigabe
            action: input_boolean.turn_off
            data: {}
          - target:
              entity_id: light.lidl_kuche
            data:
              brightness_pct: 80
              transition: 10
              rgb_color:
                - 252
                - 252
                - 252
            action: light.turn_on
          - wait_for_trigger:
              - entity_id: binary_sensor.presence_sensor_fp2_4611_presence_sensor_8
                from: "on"
                to: "off"
                trigger: state
          - delay:
              seconds: 30
          - target:
              entity_id: light.lidl_kuche
            data:
              brightness_pct: 1
              transition: 5
              rgb_color: >
                {% set color_state = states('input_text.lidl_kuche_rgb_color') |
                from_json %} {{ color_state }}
            action: light.turn_on
          - target:
              entity_id: input_boolean.lidl_kuche_speicherfreigabe
            action: input_boolean.turn_on
            data: {}
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: light.lidl_kuche
                state: "on"
              - condition: trigger
                id: anwesend_off
        sequence:
          - target:
              entity_id: light.lidl_kuche
            data:
              brightness_pct: 1
              transition: 5
              rgb_color: >
                {% set color_state = states('input_text.lidl_kuche_rgb_color') |
                from_json %} {{ color_state }}
            action: light.turn_on
          - target:
              entity_id: input_boolean.lidl_kuche_speicherfreigabe
            action: input_boolean.turn_on
            data: {}
          - delay:
              minutes: 10
          - target:
              entity_id: light.lidl_kuche
            data:
              transition: 30
            action: light.turn_off
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: light.lidl_kuche
                state: "on"
              - condition: trigger
                id: hell
        sequence:
          - target:
              entity_id: input_boolean.lidl_kuche_speicherfreigabe
            action: input_boolean.turn_on
            data: {}
          - target:
              entity_id: light.lidl_kuche
            data:
              transition: 30
            action: light.turn_off
mode: restart
max_exceeded: silent
