alias: Wohnzimmer Präsenz LED Light 1.3.1
description: "Schaltet die Lild Modlamp"
triggers:
  - entity_id:
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_5
      - binary_sensor.terrassenture_window_door_is_open
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_6
    from: "off"
    to: "on"
    trigger: state
    id: zone_on
  - entity_id:
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_1
    from: "on"
    to: "off"
    trigger: state
    id: anwesend_off
  - entity_id:
      - binary_sensor.presence_sensor_fp2_4611_presence_sensor_4
    from: "off"
    to: "on"
    trigger: state
    id: sofa
  - trigger: numeric_state
    entity_id:
      - sensor.presence_sensor_fp2_4611_light_sensor_light_level
    above: 26
    id: hell
conditions: []
actions:
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: template
                value_template: >-
                  {% set rgb = state_attr('light.lidl_wohnzimmer', 'rgb_color')
                  %} {% set color_state =
                  states('input_text.lidl_wohnzimmer_rgb_color') | from_json %}
                  {% if rgb is not none and color_state is not none %}
                    {{ [rgb[0] | int, rgb[1] | int, rgb[2] | int] != [color_state[0] | int, color_state[1] | int, color_state[2] | int]
                    and rgb != [252, 252, 252]
                    and states('light.lidl_wohnzimmer') == 'on' }}
                  {% else %}
                    false
                  {% endif %}
              - condition: numeric_state
                entity_id: light.lidl_wohnzimmer
                attribute: brightness
                below: 80
              - condition: state
                entity_id: input_boolean.lidl_wohnzimmer_speicherfreigabe
                state: "on"
        sequence:
          - data:
              entity_id: input_text.lidl_wohnzimmer_rgb_color
              value: >
                {% set rgb = state_attr('light.lidl_wohnzimmer', 'rgb_color') %}
                {{ [rgb[0], rgb[1], rgb[2]] | to_json }}
            action: input_text.set_value
  - choose:
      - conditions:
          - condition: and
            conditions:
              - condition: or
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.presence_sensor_fp2_4611_light_sensor_light_level
                    below: 26
                  - condition: numeric_state
                    entity_id: sensor.pir_wohnzimmer_illuminance
                    below: 12
              - condition: trigger
                id:
                  - zone_on
        sequence:
          - action: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.lidl_wohnzimmer_speicherfreigabe
          - alias: Turn on the light
            data:
              brightness_pct: 80
              transition: 10
              rgb_color:
                - 252
                - 252
                - 252
            action: light.turn_on
            target:
              entity_id: light.lidl_wohnzimmer
          - alias: Wait until there is no motion from device
            wait_for_trigger:
              - entity_id:
                  - binary_sensor.presence_sensor_fp2_4611_presence_sensor_5
                  - binary_sensor.presence_sensor_fp2_4611_presence_sensor_6
                  - binary_sensor.presence_sensor_fp2_4611_presence_sensor_3
                  - binary_sensor.presence_sensor_fp2_4611_presence_sensor_9
                from: "on"
                to: "off"
                trigger: state
          - alias: Wait the number of seconds that has been set
            delay:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
          - target:
              entity_id: light.lidl_wohnzimmer
            data:
              brightness_pct: 1
              transition: 5
              rgb_color: >
                {% set color_state =
                states('input_text.lidl_wohnzimmer_rgb_color') | from_json %} {{
                color_state }}
            action: light.turn_on
          - action: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.lidl_wohnzimmer_speicherfreigabe
        alias: Licht Einschalten, Hochregeln und Dimmen bei Zonen
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: light.lidl_wohnzimmer
                state: "on"
              - condition: trigger
                id:
                  - anwesend_off
        sequence:
          - action: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.lidl_wohnzimmer_speicherfreigabe
          - target:
              entity_id: light.lidl_wohnzimmer
            data:
              brightness_pct: 1
              transition: 5
              rgb_color: >
                {% set color_state =
                states('input_text.lidl_wohnzimmer_rgb_color') | from_json %} {{
                color_state }}
            action: light.turn_on
          - delay:
              hours: 0
              minutes: 10
              seconds: 0
              milliseconds: 0
          - action: light.turn_off
            metadata: {}
            data:
              transition: 30
            target:
              entity_id: light.lidl_wohnzimmer
        alias: Licht Ausschalten ohne Anwesenheit
      - conditions:
          - condition: and
            conditions:
              - condition: trigger
                id:
                  - sofa
              - condition: state
                entity_id: light.lidl_wohnzimmer
                state: "on"
              - condition: state
                entity_id: media_player.fernseher_wohnzimmer
                state: "on"
        sequence:
          - action: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.lidl_wohnzimmer_speicherfreigabe
          - alias: Wait the number of seconds that has been set
            delay:
              hours: 0
              minutes: 0
              seconds: 30
              milliseconds: 0
          - target:
              entity_id: light.lidl_wohnzimmer
            data:
              brightness_pct: 1
              transition: 5
              rgb_color: >
                {% set color_state =
                states('input_text.lidl_wohnzimmer_rgb_color') | from_json %} {{
                color_state }}
            action: light.turn_on
        alias: Licht Dimmen wenn Sofa und keine anderen Zonen
      - conditions:
          - condition: and
            conditions:
              - condition: state
                entity_id: light.lidl_wohnzimmer
                state: "on"
              - condition: trigger
                id:
                  - hell
        sequence:
          - action: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.lidl_wohnzimmer_speicherfreigabe
          - action: light.turn_off
            metadata: {}
            data:
              transition: 30
            target:
              entity_id: light.lidl_wohnzimmer
        alias: Licht Ausschalten ohne Anwesenheit
mode: restart
max_exceeded: silent
